! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert

# Biome Replacer

# 空島 (我玩整合包沒有一次去過這個地區，你也不會的對吧? :D)
terralith:skylands > null 

terralith:lavender_forest > aurorasdeco:lavender_plains
terralith:lavender_valley > aurorasdeco:lavender_plains

# 噁心的蜘蛛網洞穴
terralith:cave/infested_caves > minecraft:dripstone_caves

# 超沒用的火山
terralith:volcanic_peaks > null

# 奇異惡地 (好醜)
terralith:warped_mesa > null