#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 20 21:59:08 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=18
shaderPack=ComplementaryReimagined_r5.7.1.zip
enableShaders=false
