#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 05:27:06 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=[\u4F4E\u914D\u5149\u5F71] MakeUp-UltraFast-9.5a.zip
enableShaders=false
